Search bar for Catalogs
SE-Nex-Tech/Nex.Tech pull request #65
Opened 2024-04-06 06:25 UTC by carlmitzchel

# Search bar for Catalogs

## Details

Included a search bar that has a same styling with existing input fields.

## Juxtaposition

![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103241997/03b20135-a3ea-458f-a770-66916925a8aa)

## Et al. info

- Has no working back end functionality.
- Might cause an error due to the `onChange={(event) => searchItems(event.currentTarget.value)}` not being defined.

2024-04-07 20:35 UTC, 1123Alessandro approved these changes

2024-04-07 20:44 UTC, 1123Alessandro requested changes
Implement in games catalog too

2024-04-09 05:54 UTC, EdjinJerney approved these changes

2024-04-09 14:28 UTC, 1123Alessandro approved these changes
Search bar for games catalog implemented in another branch

2024-04-09 14:28 UTC, merged