Reports generation
SE-Nex-Tech/Nex.Tech pull request #89
Opened 2024-04-10 11:28 UTC by EdjinJerney

# Reports PDF Generation and Page Tweaks

## Details

- Added reports customization modal with preview for pdf downloading
- Added working pdf generator with actual report data
- Updated Pie Chart data in the Reports page

fix #78 

## Juxtaposition
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/ceb2cbfd-57eb-4719-9124-6ad4556bef08)
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/6cd68f61-5fd9-4d5d-a70d-bd6ca3ac42e1)
![image](https://github.com/SE-Nex-Tech/Nex.Tech/assets/103238715/b5042b8b-dda3-49c7-a58a-d186817e5f58)

2024-04-10 11:36 UTC, 1123Alessandro requested changes
Delete `prisma/migrations` folder

Disregard `yarn.lock`

2024-04-10 12:24 UTC, KyleZrey approved these changes

2024-04-10 17:12 UTC, 1123Alessandro requested changes
Remove `prisma/migrations`

2024-04-11 07:45 UTC, 1123Alessandro approved these changes

2024-04-11 07:53 UTC, carlmitzchel approved these changes

2024-04-11 07:54 UTC, merged