Superadmin route protection
SE-Nex-Tech/Nex.Tech pull request #96
Opened 2024-04-11 15:41 UTC by carlmitzchel

# Superadmin route protection

## Details

Created a new API to fetch all the admins with a type of `superadmin`

It is then compared to the `session.user.email` If it does not match, it will return `<Unauthenticated/>`

2024-04-11 15:54 UTC, EdjinJerney approved these changes

2024-04-11 20:16 UTC, 1123Alessandro commented on src/app/(general)/api/superadmin/valid/route.js
> +    where: { type: "superadmin" },
Would be better to fetch specific superadmin by including the email. Fetching all superadmins can be a security risk by checking the fetch response.

2024-04-11 20:18 UTC, 1123Alessandro requested changes
Check file comments,

Fetch specific superadmin

2024-04-12 01:47 UTC, 1123Alessandro approved these changes

2024-04-12 02:33 UTC, merged